"""Initial Growth Engine schema

Revision ID: 8dd1d61b8349
Revises: 
Create Date: 2026-02-26 01:08:03.408999
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8dd1d61b8349'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', name='campaignstatus'), nullable=False),
    sa.Column('platform_filter', sa.Enum('YOUTUBE', 'SKOOL', 'PATREON', 'WEBSITE', 'TIKTOK', 'INSTAGRAM', name='platform'), nullable=True),
    sa.Column('niche_filter', sa.JSON(), nullable=True),
    sa.Column('min_followers', sa.Integer(), nullable=False),
    sa.Column('email_sequence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'SCRAPED', 'CONTENT_GENERATED', 'STORE_CREATED', 'EMAIL_SENT', 'CLAIMED', 'REJECTED', name='prospectstatus'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('primary_platform', sa.Enum('YOUTUBE', 'SKOOL', 'PATREON', 'WEBSITE', 'TIKTOK', 'INSTAGRAM', name='platform'), nullable=False),
    sa.Column('primary_platform_id', sa.String(length=255), nullable=False),
    sa.Column('primary_platform_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('banner_image_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('niche_tags', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=False),
    sa.Column('content_count', sa.Integer(), nullable=False),
    sa.Column('brand_colors', sa.JSON(), nullable=True),
    sa.Column('kliq_application_id', sa.Integer(), nullable=True),
    sa.Column('kliq_store_url', sa.String(length=500), nullable=True),
    sa.Column('claim_token', sa.String(length=255), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('store_created_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('campaign_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('email_status', sa.Enum('PENDING', 'SENT', 'OPENED', 'CLICKED', 'BOUNCED', 'UNSUBSCRIBED', name='emailstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('brevo_message_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('YOUTUBE', 'SKOOL', 'PATREON', 'WEBSITE', 'TIKTOK', 'INSTAGRAM', name='platform'), nullable=False),
    sa.Column('platform_id', sa.String(length=255), nullable=False),
    sa.Column('platform_url', sa.String(length=500), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('YOUTUBE', 'SKOOL', 'PATREON', 'WEBSITE', 'TIKTOK', 'INSTAGRAM', name='platform'), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('engagement_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('YOUTUBE', 'SKOOL', 'PATREON', 'WEBSITE', 'TIKTOK', 'INSTAGRAM', name='platform'), nullable=False),
    sa.Column('tier_name', sa.String(length=255), nullable=False),
    sa.Column('price_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('content_metadata', sa.JSON(), nullable=True),
    sa.Column('source_content_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['source_content_id'], ['scraped_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_content')
    op.drop_table('scraped_pricing')
    op.drop_table('scraped_content')
    op.drop_table('platform_profiles')
    op.drop_table('campaign_events')
    op.drop_table('prospects')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
